export const UAF_OPERATION_TYPES = {
  DISCOVER: "DISCOVER",
  DISCOVER_RESULT: "DISCOVER_RESULT",
  CHECK_POLICY: "CHECK_POLICY",
  CHECK_POLICY_RESULT: "CHECK_POLICY_RESULT",
  UAF_OPERATION: "UAF_OPERATION",
  UAF_OPERATION_RESULT: "UAF_OPERATION_RESULT",
  UAF_OPERATION_COMPLETION_STATUS: "UAF_OPERATION_COMPLETION_STATUS"
};

export const RELYING_PARTY_URL_SCHEME = 'com.ultraauth.demoapp://';
export const FIDO_UAF_APP_URL_SCHEME = 'com.ultraauth://';